---
exclude_paths:
  - '.git/'
  - 'files/'

kinds:
  - tasks: 'ansible/tasks/*.{yml,yaml}'
  - vars: 'ansible/vars/*.{yml,yaml}'
  - vars: 'defaults/*.{yml,yaml}'
  - meta: 'meta/main.{yml,yaml}'
  - yaml: '.ansible-lint'
  - yaml: 'ansible/playbooks/*.{yml,yaml}'
  - yaml: 'collections/requirements.yml'

loop_var_prefix: '^(__|{role}_)'
max_block_depth: 20
offline: true
profile: 'production'
skip_action_validation: false
skip_list: []
task_name_prefix: '{stem} | '
use_default_rules: true
var_naming_pattern: '^[a-z_][a-z0-9_]*$'
warn_list:
  - 'experimental'
write_list:
  - 'none'
