---
extends: default

rules:
  braces:
    # Keeping 0 min-spaces to not error on empty collection definitions
    min-spaces-inside: 0
    # Allowing one space inside braces to improve code readability
    max-spaces-inside: 1

  brackets:
    # Defaults
    # Keeping 0 min-spaces to not error on empty collection definitions
    min-spaces-inside: 0
    # Allowing one space inside braces to improve code readability
    max-spaces-inside: 1

  colons:
    max-spaces-before: 0
    # Allowing more than one space for code readability
    max-spaces-after: -1

  comments:
    min-spaces-from-content: 1

    # Disabling to allow for code comment blocks and #!/usr/bin/ansible-playbook
    require-starting-space: false

  comments-indentation: enable

  indentation:
    # Requiring 2 space indentation
    spaces: 2
    # Requiring consistent indentation within a file, either indented or not
    indent-sequences: consistent

  line-length:
    max: 100

  octal-values:
    forbid-explicit-octal: true
    forbid-implicit-octal: true

  truthy: disable
