---
- name: Configure SSH
  hosts: local
  tasks:
    - name: Create .ssh folder
      ansible.builtin.file:
        path: ~/.ssh/
        state: directory

    - name: Symlink SSH config
      ansible.builtin.file:
        src: "{{ playbook_dir }}/../../ssh/config"
        dest: ~/.ssh/config
        state: link
        force: true

    - name: Symlink SSH public key
      ansible.builtin.file:
        src: "{{ playbook_dir }}/../../ssh/id_ed25519.pub"
        dest: ~/.ssh/id_ed25519.pub
        state: link
        force: false
      ignore_errors: true

    - name: Symlink SSH private key
      ansible.builtin.file:
        src: "{{ playbook_dir }}/../../ssh/id_ed25519"
        dest: ~/.ssh/id_ed25519
        state: link
        force: false
      ignore_errors: true
