---
- name: Install zsh from Homebrew
  hosts: local
  vars:
    - user_home: "$HOME"
    - zsh_dir: "{{ playbook_dir }}/../../zsh"
  tasks:
    - name: Install zsh
      community.general.homebrew:
        name: zsh
        state: present

    - name: Check for .zshrc
      stat: path="{{ user_home }}/.zshrc"
      register: zshrc_stat

    - name: Back up .zshrc
      command: mv ~/.zshrc ~/.zshrc.bak
      args:
        creates: "{{ user_home }}/.zshrc.bak"
      when: zshrc_stat.stat.exists

    - name: Symlink .zshrc to home-directory
      ansible.builtin.file:
        src: "{{ zsh_dir }}/.zshrc"
        dest: "{{ user_home }}/.zshrc"
        state: link
        follow: false
        force: true

    - name: Link .zprofile to home-directory
      ansible.builtin.file:
        src: "{{ zsh_dir }}/.zprofile"
        dest: "{{ user_home }}/.zprofile"
        state: link
        follow: false
        force: true
