---
- name: Set up a new machine or update settings on current
  hosts: local
  gather_facts: true

- name: Configure and symlink SSH config and keys
  ansible.builtin.import_playbook: configure-ssh.yml

- name: Install and configure git
  ansible.builtin.import_playbook: install-git.yml

- name: Install zsh
  ansible.builtin.import_playbook: install-zsh.yml

- name: Create other dotfiles
  ansible.builtin.import_playbook: create-dotfiles.yml

