---
- name: Set up a new machine or update settings on current
  hosts: local
  gather_facts: true

- name: Install and configure git
  ansible.builtin.import_playbook: install-git.yml

- name: Install fonts
  ansible.builtin.import_playbook: install-fonts.yml

- name: Install zsh
  ansible.builtin.import_playbook: install-zsh.yml

- name: Install Brew packages
  ansible.builtin.import_playbook: install-homebrew-packages.yml
  when: ansible_architecture == "darwin"

- name: Install Mac App Store apps
  ansible.builtin.import_playbook: install-mac-app-store-apps.yml
  when: ansible_architecture == "darwin"

- name: Configure and symlink SSH config and keys
  ansible.builtin.import_playbook: configure-ssh.yml

- name: Configure vim
  ansible.builtin.import_playbook: configure-vim.yml

- name: Configure tmux
  ansible.builtin.import_playbook: configure-tmux.yml

- name: Configure todo.txt
  ansible.builtin.import_playbook: configure-todo.yml

- name: Configure Finder
  ansible.builtin.import_playbook: configure-finder.yml

- name: Symlink other dotfiles
  ansible.builtin.import_playbook: symlink-dotfiles.yml

- name: Reload shell
  ansible.builtin.import_playbook: reload-shell.yml

